name: Hello World Workflow

on:
  push:
    branches:
      - main  # Change this to your target branch if needed

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Echo text
        run: echo "Hello, world!"
